name: AK Codelab Journal Sync

on:
  schedule:
    - cron: '0 */3 * * *'  # every 3 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-journal:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        pip install gspread pandas google-auth

    - name: Write service_account.json
      run: |
        printf "%s" "${{ secrets.GDRIVE_CREDENTIALS }}" > service_account.json

    - name: Verify JSON
      run: |
        python -m json.tool service_account.json

    - name: Run sync script
      run: python scripts/sync_codelab_json.py

    - name: Commit & push updated JSON
      run: |
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        git add journal-data.json || echo "No file to add"
        git diff --staged --quiet || git commit -m "Update journal-data.json [bot]"
        git push

