name: Sync Google Sheet to JSON

on:
  workflow_dispatch: # manual run
  schedule:
    - cron: '0 0 * * *'  # runs daily at midnight UTC

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pandas

      - name: Run sync script
        run: |
          python script/sync_codelab_json.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ak_codelab_data.json
          git commit -m "Update ak_codelab_data.json [bot]" || echo "No changes to commit"
          git push